name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Git Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass openfortivpn

    - name: Connect to VPN
      run: |
        sudo openfortivpn vpnssl.upm.es --username=alvaro.cabo@alumnos.upm.es --password=${{ secrets.VPN_PW }} &

    - name: Wait for VPN to Connect
      run: sleep 5s

    - name: SSH to Server and Pull Changes
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 22
        script: |
          # Set proxy
          git config --global http.proxy http://proxy.fi.upm.es:8080
          git config --global https.proxy http://proxy.fi.upm.es:8080

          # Check if Kaska-SSDD directory exists
          if [ -d "Kaska-SSDD" ]; then
            # Kaska-SSDD directory exists, do a git pull
            cd DATSI
            git pull
            cd ..
          else
            # Kaska-SSDD directory doesn't exist, do a git clone
            git clone https://{{secrets.TOKEN_GITHUB}}@github.com/alvarocaboUPM/Kaska-SSDD/
            cp -r Kaska-SSDD/DATSI .
          fi


    - name: Run Script on Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          yes s | entrega.sd kaska.2023
